### ISSUE TITLE
Multi-video support for pop out player

### ISSUE THREAD

**Issue by pornganizer** [pornganizer/PGV5#15]
The pop out player should be able to play 4 different videos simultaneously all with independent controls.

**Comment by framedevelop** [comment]
Please consider making the multiple videos playing at one time a right click selection. Most of time when surfing through videos you want to replace the currently playing video rather than adding another pop out. The pop out should kill the already playing video unless you right click and select play in additional window (or something like that)

**Comment by pornganizer** [comment]
the right click menu of a scene in the main list has options to replace a currently playing video
more enhancements to the scene details pane in this regard coming soon

**Comment by pornganizer** [comment]
hijacked by the "home view"
