### ISSUE TITLE
Move imported files to appropriate directory

### ISSUE THREAD

**Issue by pornganizer** [pornganizer/PGV5#5]
Imported files should be able to be moved automatically to an appropriate directory should it exist, based on finding directories matching tags like star/website/dvd/category/theme.

**Comment by GernBlanston12** [comment]
Don't know if I like the idea, since it sets up a lot of binary/directory tree style rules for file storage, and getting away from that was the entire reason to get into db for it all in the first place.  What I mean is: I chose to store my collection in folders named for Website/Production Company and DVD production.  My collection spans several drives. How those drives fill up over time isn't a directory-led process, so I end up with a folder for a given Website repeated on 3 different drives, each with different movies in them. PG means I don't have to be concerned with this ; ) because I'm not bound by directories, rather any identifying features I choose to aggregate by in the moment. If I sort by the website, I get a view of those videos from that website, regardless of drive they're on. Therefore, I don't know that I want PG to have "rules" about where I'm storing my files. How would PG know that the bulk of my Babes videos are on one drive, but that drive is full, and maybe it needs to start another Babes directory on another drive if it wants more Babes videos stored, etc.  Are you just letting PG rip on a drive at a time, where any import videos go to whatever drive PG is currently filling up? I guess it would have to fill drives linearly, in this case, only checking for presence of the "correct" directory on current drive it's filling?

**Comment by pornganizer** [comment]
so the way this works is it presents a list of folders that PG believes are appropriate
you pick the folder, it moves the scene
this is not yet implemented in bulk

**Comment by pornganizer** [comment]
functionality is in place, further enhancements possible
you can move a file individually, there is also an option to move a file automatically on import
